reservation_platform/booking/urls.py
from django.urls import path
from . import views
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('home/', views.home),
    path('booking/', views.booking_form),
    path('booking/modify/<int:id>', views.booking_form),
    path('booking/delete/<int:id>', views.delete_booking),
    path('ressource/', views.ressource_form),
    path('ressource/delete/<int:id>', views.delete_ressource)
]

reservation_platform/connect/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.connexion)
]

reservation_platform/reservation_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from connect import views
from booking import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('connect/', include('connect.urls')),
    path('', include('booking.urls'))
]

reservation_platform/booking/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
import pytz
from connect.models import Profil

# Register your models here.
class Ressource(models.Model):
    RESRC_TYPES = (
        ("L", "Loft"),
        ("S", "Studios"),
        ("H", "House")
    )
    name = models.CharField(max_length=50)
    res_type = models.CharField(max_length=10, choices=RESRC_TYPES)
    location = models.CharField(max_length=50)
    capacity = models.IntegerField(choices=zip(range(1,10), range(1,10)))
    comments = models.TextField(null=True)
    
    def check_availabilities(self, start_date, end_date):
        reservations = self.related_reservations.all()
        for res in reservations:
            if ((res.start_date <= end_date) and (res.end_date  >= start_date)):
                return False
        return True
        
    def add_booking(self, start_date, end_date):
        if isinstance(start_date, datetime) and isinstance(end_date, datetime):
            if self.check_availabilities(start_date, end_date):
                return True
        return False

    def __str__(self):
        return self.name


class Reservation(models.Model):
    RES_STATUS = (
        ("Passed", "#222"),
        ("Current", "darkgreen"),
        ("Incoming", "lightgreen")
    )
    title = models.CharField(max_length=50)
    start_date = models.DateTimeField(default=timezone.now, verbose_name="Start Date")
    end_date = models.DateTimeField(default=timezone.now, verbose_name="End Date")
    author = models.ForeignKey(Profil, null=True, blank=True, on_delete=models.CASCADE, related_name="profil")
    ressource = models.ForeignKey(Ressource, null=True, on_delete=models.CASCADE, related_name="related_reservations")
    status = models.CharField(max_length=10, choices=RES_STATUS)

    def set_title(self, new_title):
        self.title = new_title

    def status_update(self):
        '''Check status of one reservation'''
        today = datetime.now(timezone.get_current_timezone())
        if self.end_date < today:
            self.status = Reservation.RES_STATUS[0][0]
        elif self.start_date < today and self.end_date > today:
            self.status = Reservation.RES_STATUS[1][0]
        else:
            self.status = Reservation.RES_STATUS[2][0]
        self.save()

    def __str__(self):
        return "RESERVATION {}\n ({}, {}) by {}".format(self.title, self.start_date, self.end_date, self.author)

reservation_platform/connect/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import pytz

TIME_ZONE = (
    ('Europe/Berlin', 'Europe/Berlin'), 
    ('Europe/London', 'Europe/London'),
    ('Europe/Paris', 'Europe/Paris'),
    ('Australia/Melbourne', 'Australia/Melbourne')
)

LANGUAGE = (
    ('fr', 'Francais'),
    ('en', 'English')
)

class Profil(models.Model):
    ''' This class extend "User" native classs, and add timezone and language for each user'''
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, related_name="profil")  # La liaison OneToOne vers le modèle User
    timezone = models.CharField(max_length=20, choices=TIME_ZONE, null=True, blank=True)
    language = models.CharField(max_length=10, choices=LANGUAGE, null=True, blank=True)

    def __str__(self):
        return "{}".format(self.user.username)

reservation_platform/connect/forms.py
from django import forms

class ConnectionForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(label="password", widget=forms.PasswordInput)

reservation_platform/connect/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from .forms import ConnectionForm
from booking.models import Reservation, Ressource
from booking.views import booking_form
from django.http import HttpResponse, HttpResponseRedirect, Http404



def connexion(request, error_message = ""):
    '''A simple authentification view to access login form'''
    if request.user.is_authenticated:
        logout(request)
        return render(request, "login.html", locals())

    if request.method == "POST":
        form = ConnectionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            # check if informations correspond to one registered user
            user = authenticate(username = username, password=password)
            if user: 
                login(request, user)
                error = False
                return HttpResponseRedirect("/home")
            else:
                error = True
    else:
        form = ConnectionForm()
    return render(request, "login.html", locals())

reservation_platform/connect/templates/connect/home.html
    {% extends "base.html" %}
    <!DOCTYPE html>
    <html>
    <head>
    </head>
    <body>
        {%load tz%}
        {%block content%}
        <div class="centered_div">
            <h2> {{welcome}} <span style=" color:lightgreen;">{{user_profil}}</span></h2> 
            <div class="date"> {{today}}</div>
            <div class="date"> {{zone}} ({{user_language}})</div>
            
            <br>
            <h3> Réservations </h3>
            <p class="basic">{{infos}}</p>
            <table>
                <tr>
                    <th style="width:5%">Status</th>
                    <th style="width:30%;">Label</th>
                    <th style="width:15%;">Ressource</th>
                    <th style="width:20%;">Start</th>
                    <th style="width:20%;">End</th>
                    <th style="width:5%;"></th>
                    <th style="width:5%;"></th>
            </tr>   
            {% for res in reservation_list %}
                <tr class="clickable">
                    <td style="text-align: center;">
                            <span class="dot" style="background:{{res.get_status_display}};"></span>
                    </td>
                    <td>
                        {%if user.is_staff %}
                            <span style=" color:rgb(142, 211, 142);">[{{res.author}}]</span>
                        {%endif%}
                        {{res.title}}
                    </td>
                    <td>{{res.ressource}}</td>
                    <td>{{res.start_date|localtime}}</td>
                    <td>{{res.end_date|localtime}}</td>
                    <td style="text-align:center;">
                        {%if res.status == "Incoming"%}
                            <a href="/booking/modify/{{res.id}}">modify</a>
                        {%endif%}
                    </td>
                    <td style="text-align:center;">
                        {%if res.status == "Passed" or res.status == "Incoming" %}
                            <a href="/booking/delete/{{res.id}}">X</a>
                        {%endif%}
                    </td>
                </tr>
            {% endfor %}
            </tr> 
        </table>
        <div style="margin-top:20px;padding-left:70%;">
            <a id="add_resa" class="cust_button" href="/booking"> Ajouter une réservation </a>
        </div>

        <br>
        <h3> Ressources Disponibles </h3>
            <table>
                <tr>
                    <th style="width:40%;">Name</th>
                    <th style="width:20%;">Type</th>
                    <th style="width:20%;">Location</th>
                    <th style="width:15%;">Capacity</th>
                    <th style="width:5%;"></th> 
                </tr>   
                {% for resrc in ressource_list %}
                    <tr class="clickable">
                        <td>{{resrc.name}}</td>
                        <td>{{resrc.get_res_type_display}}</td>
                        <td>{{resrc.location}}</td>
                        <td style="text-align:center;">{{resrc.capacity}}</td>
                        {%if user.is_staff %}
                        <td style="text-align:center;"><a href="/ressource/delete/{{resrc.id}}">X</a></td>
                        {%endif%}
                    </tr>
                {% endfor %}
                </tr> 
            </table>
            {%if user.is_staff %}
            <div style="margin-top:20px;padding-left:70%;">
                    <a id="add_resrc" class="cust_button" href="/ressource"> Ajouter une ressource </a>
            </div>
            {%endif%}
    </div>
        
    {%endblock%}
</body>

</html>

reservation_platform/connect/templates/connect/login.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
<head>
</head>
<body>

    {%block logout%}
    {%endblock%}
    {%block content%}
    <div class="centered_div">
        <h3 style="text-align: center;">CONNEXION</h3>
    
        <form method="post">
        {% csrf_token %} <!--security ensurance-->
            <p><label for="username"></label> <input type="text" name="username" maxlength="50" placeholder="Username" /></p>
            <p><label for="password"></label> <input type="text" name="password" maxlength="50" placeholder="Password" /></p>
            {% if error %}<p class="login_KO"> {{error_message}} </p> {% endif %}
            {% if error == False %} <p class="login_OK"> You are welcome {{username}}</p>{% endif %} 
    
            <input type="submit" value="Submit" />
        </form>
    </div>
    {%endblock%}
</body>
</html>