reservation_platform/booking/urls.py
from django.urls import path
from . import views
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('home/', views.home),
    path('booking/', views.booking_form),
    path('booking/modify/<int:id>', views.booking_form),
    path('booking/delete/<int:id>', views.delete_booking),
    path('ressource/', views.ressource_form),
    path('ressource/delete/<int:id>', views.delete_ressource)
]

reservation_platform/reservation_platform/urls.py
from django.contrib import admin
from django.urls import path, include
from connect import views
from booking import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('connect/', include('connect.urls')),
    path('', include('booking.urls'))
]

reservation_platform/booking/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
import pytz
from connect.models import Profil

# Register your models here.
class Ressource(models.Model):
    RESRC_TYPES = (
        ("L", "Loft"),
        ("S", "Studios"),
        ("H", "House")
    )
    name = models.CharField(max_length=50)
    res_type = models.CharField(max_length=10, choices=RESRC_TYPES)
    location = models.CharField(max_length=50)
    capacity = models.IntegerField(choices=zip(range(1,10), range(1,10)))
    comments = models.TextField(null=True)
    
    def check_availabilities(self, start_date, end_date):
        reservations = self.related_reservations.all()
        for res in reservations:
            if ((res.start_date <= end_date) and (res.end_date  >= start_date)):
                return False
        return True
        
    def add_booking(self, start_date, end_date):
        if isinstance(start_date, datetime) and isinstance(end_date, datetime):
            if self.check_availabilities(start_date, end_date):
                return True
        return False

    def __str__(self):
        return self.name


class Reservation(models.Model):
    RES_STATUS = (
        ("Passed", "#222"),
        ("Current", "darkgreen"),
        ("Incoming", "lightgreen")
    )
    title = models.CharField(max_length=50)
    start_date = models.DateTimeField(default=timezone.now, verbose_name="Start Date")
    end_date = models.DateTimeField(default=timezone.now, verbose_name="End Date")
    author = models.ForeignKey(Profil, null=True, blank=True, on_delete=models.CASCADE, related_name="profil")
    ressource = models.ForeignKey(Ressource, null=True, on_delete=models.CASCADE, related_name="related_reservations")
    status = models.CharField(max_length=10, choices=RES_STATUS)

    def set_title(self, new_title):
        self.title = new_title

    def status_update(self):
        '''Check status of one reservation'''
        today = datetime.now(timezone.get_current_timezone())
        if self.end_date < today:
            self.status = Reservation.RES_STATUS[0][0]
        elif self.start_date < today and self.end_date > today:
            self.status = Reservation.RES_STATUS[1][0]
        else:
            self.status = Reservation.RES_STATUS[2][0]
        self.save()

    def __str__(self):
        return "RESERVATION {}\n ({}, {}) by {}".format(self.title, self.start_date, self.end_date, self.author)

reservation_platform/booking/forms.py
# write forms here
from django import forms
from .models import Reservation, Ressource
from django.utils import timezone
import datetime


class ReservationForm(forms.ModelForm):
    ''' Reservation form used in /booking'''
    class Meta:
        model=Reservation
        fields=('title', 'start_date', 'end_date', 'ressource')

    def clean(self):
        cleaned_data = super(ReservationForm, self).clean()
        start = cleaned_data['start_date']
        end = cleaned_data['end_date']
        ressource = cleaned_data['ressource']

        # check if there is no anachronism betwen start and end dates
        if start and end: # si les fields sont cleans
            if start >= end:
                raise forms.ValidationError("Unvalid dates !")
        # check if ressource is not booked yet by another user
        if ressource:
            if ressource.add_booking(start, end) == False:
                raise forms.ValidationError("Dates are already booked!")      
        else:
            raise forms.ValidationError("Unvalid Ressource !")
        return cleaned_data



class RessourceForm(forms.ModelForm):
    ''' Ressource form used in /ressource (only available for admin)'''
    class Meta:
        model=Ressource
        fields = ('name', 'res_type', 'location', 'capacity')

reservation_platform/booking/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from datetime import datetime
from .forms import ReservationForm, RessourceForm
from .models import Reservation, Ressource
from django.contrib import messages 
from django.utils import timezone
import pytz
import sys
import connect
from connect.models import Profil
from django.utils.translation import ugettext as _
from django.utils.translation import get_language, activate

# these two class below just check user authenticated
def check_auth(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect('/connect')

def check_admin_auth(request):
    if not request.user.is_staff:
        return HttpResponseRedirect('/connect')

def home(request):
    '''View to render /home.html template'''
    check_auth(request)
    user_profil = request.user.profil
    today = timezone.localtime()
    zone = timezone.get_current_timezone()
    
    # TOFIX : here activate language do not works ! 
    activate(request.user.profil.language)
    user_language = get_language()

    # translated paragraphs
    welcome = _("Bienvenue")
    infos = _("Voici l'ensemble de vos réservations sur notre plateforme. Vous \
            pouvez les modifier avec le bouton 'modify' ou encore les supprimer \
            avec le bouton 'X'.")

    # get reservation list to display depending on authenticated user
    reservation_list = Reservation.objects.filter(author=user_profil) if not request.user.is_staff else Reservation.objects.all()
    reservation_list = list(reservation_list.order_by("-start_date")) # sort by dates
    ressource_list = list(Ressource.objects.all())

    # update status each time to check if reservation is "passed", 'current' or 'incoming'
    for res in reservation_list:
        res.status_update()
    return render(request, "home.html", locals())


# id est à 1 que si 
def booking_form(request, id=-1):
    '''View to access booking form'''
    check_auth(request)
    error_message = ""
    form = ReservationForm(request.POST or None)
    ressources = Ressource.objects.all() # get all ressources
    
    # if form is valid then we can create a new Reservation instance
    if form.is_valid(): 
        title = form.cleaned_data['title']
        ressource = form.cleaned_data['ressource']
        start_date = form.cleaned_data['start_date']
        end_date = form.cleaned_data['end_date']

        reservation = Reservation() if id < 0 else Reservation.objects.get(id=id)
        if reservation:
            reservation.title = title
            reservation.ressource = ressource       
            reservation.start_date = start_date
            reservation.end_date = end_date
            reservation.author = request.user.profil
            reservation.status_update()
            reservation.save()
            return HttpResponseRedirect('/home')
    if form.errors:
        error_message = "Entrées du Formulaire non valides"
    return render(request, 'booking_form.html', locals())    

def delete_booking(request, id):
    '''Simple function to delete one reservation'''
    check_auth(request)
    reservation = Reservation.objects.get(id=id)
    
    # delete only if reservation exist
    if reservation:
        reservation.delete()
    return HttpResponseRedirect('/home')


def ressource_form(request):
    # ressource form is available onlu for admin users
    check_admin_auth(request)
    if request.user.has_perm("booking.create_ressource"):
        time =  datetime.now()
        form = RessourceForm(request.POST or None)
        ressources = Ressource.objects.all() # get all ressources
        ressource_types = Ressource.RESRC_TYPES

        # if form is valid then we can create a new Ressource instance
        if form.is_valid(): 
            name = form.cleaned_data['name']
            res_type = form.cleaned_data['res_type']
            location = form.cleaned_data['location']
            capacity = form.cleaned_data['capacity']

            ressource = Ressource()
            ressource.name = name
            ressource.res_type = res_type
            ressource.location = location
            ressource.capacity = capacity
            ressource.save()

            return HttpResponseRedirect('/home')
         
        error_message = form.errors
    return render(request, 'ressource_form.html', locals())    

def delete_ressource(request, id):
    check_admin_auth(request)
    # check if user has permission to delete a ressource
    if request.user.has_perm("booking.delete_ressource"):
        ressource = Ressource.objects.get(id=id)
        if ressource:
            ressource.delete()
        
    return HttpResponseRedirect('/home')
    

reservation_platform/booking/templates/booking/booking_form.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    {%block content%}
    <div class="centered_div">

        <h2>AJOUTER UNE RESERVATION</h2>

        <form method="post">
            {% csrf_token %} 
            <p><label for="id_titre"></label>
                 <input id="id_titre" type="text" name="title" maxlength="100" placeholder="Titre de la réservation"/>    
            </p>
            
                <label for="id_ressource"></label>
                <p style="color:#333;margin-bottom:0px;"> Sélection Ressource </p>
                <select name="ressource">
                        {% for resrc in ressources %}
                        <option  value="{{resrc.id}}">{{resrc.id}}-{{resrc.name}}</option>
                        {% endfor %}
                </select>
                <div style="float:left;">   
                    <label for="id_start_date"></label>
                        <p style="color:#333; margin-bottom:0px;"> début </p>
                        <input id="id_start_date" type="date" name="start_date"/>
                </div>

                <div style="float:right;">
                    <label for="id_end_date"></label>
                        <p style="color:#333;margin-bottom:0px;"> fin </p>  
                        <input id="id_end_date" type="date" name="end_date"/>
                </div>
                
                <div style="font-size:70%;color:rgb(245, 71, 71);">
                    <p style="color:rgb(245, 71, 71);">{{error_message}}</p>
                </div>

            <div style="padding-top:100px;">
                <input class="cust_button" type="submit" value="Submit"/>
                <a class="cust_button" href="/home">Cancel</a>
            </div>
        </form>
    </div>
    {%endblock%}
</body>
</html>

reservation_platform/booking/templates/booking/ressource_form.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
<head>
</head>
<body>
    {%block content%}
    <div class="centered_div">

        <h3 style="text-align: center;">AJOUTER UNE RESSOURCE</h3>
        <div class="date"> {{time}}</div>

        <form method="post">
            {% csrf_token %} 
            <p><label for="id_name"></label>
                <input id="id_name" type="text" name="name" maxlength="50" placeholder="Nom de la ressource"/>    
            </p>
            <p><label for="id_location"></label>
                <input id="id_location" type="text" name="location" maxlength="50" placeholder="Adresse"/>    
            </p>

            <p><label for="id_capacity" class="resrc_selector"></label>
                <input id="id_capacity" type="number" name="capacity" maxlength="50" min="1" max="10" placeholder="Capacité"/>    
            </p>
            <p style="color:#333;margin-bottom:0px;"> Type de Ressource </p>
            <select name="res_type">
                {% for r in ressource_types %}
                    <option value="{{r.0}}">{{r.1}}</option>
                {%endfor%}
            </select> 

            <div style="padding-top:100px;">
                <input class="cust_button" type="submit" value="Submit"/>
                <a class="cust_button" href="/home">Cancel</a>
            </div>
        </form>
    </div>
    {%endblock%}
</body>
</html>